\ ### Autogenerated Hello script. Created @ Sat Aug 17 11:04:34 2019
\ Created using BSV Editor
\ Contents were modified (slightly) by hand to make it compatible with Tape Recorder
\ See hack.hll and hack.hll.script for original version

\ ###
\ ### cnt = 0x02;
\ ###
0x02
OP_TOALTSTACK

\ ###
\ ### for i in [1 .. 2]
\ ###
0x01
OP_TOALTSTACK

\ ###
\ ### 
\ ### 	cnt = cnt + i;
\ ###
OP_FROMALTSTACK
OP_FROMALTSTACK
OP_DUP
OP_TOALTSTACK
OP_SWAP
OP_TOALTSTACK
OP_FROMALTSTACK
OP_DUP
OP_TOALTSTACK
OP_ADD
OP_FROMALTSTACK
OP_FROMALTSTACK
OP_DROP
0x01
OP_ROLL
OP_TOALTSTACK
OP_TOALTSTACK
0x02
OP_FROMALTSTACK
OP_DROP
OP_TOALTSTACK

\ ###
\ ### 
\ ### 	cnt = cnt + i;
\ ###
OP_FROMALTSTACK
OP_FROMALTSTACK
OP_DUP
OP_TOALTSTACK
OP_SWAP
OP_TOALTSTACK
OP_FROMALTSTACK
OP_DUP
OP_TOALTSTACK
OP_ADD
OP_FROMALTSTACK
OP_FROMALTSTACK
OP_DROP
0x01
OP_ROLL
OP_TOALTSTACK
OP_TOALTSTACK

\ End of compiled script
\ Added this check results for correctness
\ result and loop index are left on the stack so gotta pop them off
OP_FROMALTSTACK
OP_DROP
OP_FROMALTSTACK
OP_5 OP_EQUAL 
cr .